// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.coacha.gomanager.model;

import com.coacha.gomanager.model.Player;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Player_Roo_Configurable {
    
    declare @type: Player: @Configurable;
    
}
